config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :movies, only: :index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  include PgSearch::Model
  multisearchable against: [:title, :syllabus]
  # pg_search_scope :search_by_title_and_syllabus,
  #   against: [ :title, :syllabus ],
  #   associated_against: {
  #     director: [ :first_name, :last_name ]
  #   },
  #   using: {
  #     tsearch: { prefix: true } # <-- now `superman batm` will return something!
  #   }
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title, :syllabus]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query].present?
      @movies = Movie.search_by_title_and_syllabus(params[:query])

      # sql_query = " \
      #   movies.title @@ :query \
      #   OR movies.syllabus @@ :query \
      #   OR directors.first_name @@ :query \
      #   OR directors.last_name @@ :query \
      # "
      # @movies = Movie.joins(:director).where(sql_query, query: "%#{params[:query]}%")
    else
      @movies = Movie.all
    end
  end
end

# USER ---> goes to the FORM --> write QUERY  -->
# QUERY GOES TO '/movies' --> FILTER THE DATA BY FORM DATA (QUERY)
# --> FILTER THE MOVIE DATA

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:query].present?
      @results = PgSearch.multisearch(params[:query])
    else
      @results = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <%= form_tag movies_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a movie"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div id="movies">
        <% @movies.each do |movie| %>
          <h4><%= movie.title %></h4>
          <h5>Director: <%= movie.director.first_name %> <%= movie.director.last_name %></h5>
          <p><%= movie.syllabus %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <%= form_tag root_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Type a keyword"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div id="movies">
        <% @results.each do |result| %>
          <% if result.searchable_type == 'Movie' %>
            <% movie = result.searchable %>
            <h4><%= movie.title %></h4>
            <h5>Director: <%= movie.director.first_name %> <%= movie.director.last_name %></h5>
            <p><%= movie.syllabus %></p>            
          <% else %>
            <% tv_show = result.searchable %>
            <h4><%= tv_show.title %></h4>
            <p><%= tv_show.syllabus %></p>            
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>